//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollecumentData
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public File()
        {
            this.Histories = new HashSet<History>();
            this.Sharings = new HashSet<Sharing>();
        }
    
        public string ID { get; set; }
        public string Description { get; set; }
        public string CreatorID { get; set; }
        public System.DateTime Date_Creation { get; set; }
        public string UpdateID { get; set; }
        public Nullable<System.DateTime> Date_Update { get; set; }
        public int ExtensionID { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string Remark { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Extension Extension { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<History> Histories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sharing> Sharings { get; set; }
    }
}
