//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollecumentData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sharing
    {
        public string FileID { get; set; }
        public string TZ { get; set; }
        public int ShareLevelID { get; set; }
    
        public virtual File File { get; set; }
        public virtual Permission Permission { get; set; }
        public virtual User User { get; set; }
    }
}
